"""
<<<<<<<< HEAD:django_blog/django_blog/settings.py
Django settings for django_blog project.
========
Django settings for advanced_api_project project.
>>>>>>>> 01a850dae2c214b543d28b8224f3639fdfa888ed:advanced_api_project/settings.py

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<<< HEAD:django_blog/django_blog/settings.py
SECRET_KEY = 'django-insecure-lu+(5$jol@+1*vke)k&)%mm84z%7l@c$kdxioe*o96(!#$$xx@'
========
SECRET_KEY = 'django-insecure-_=-rt&x#^)#)*8u@(jcka$7@$eqshvbbfk@fd7u(x^#rq$0^$c'
>>>>>>>> 01a850dae2c214b543d28b8224f3639fdfa888ed:advanced_api_project/settings.py

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<<< HEAD:django_blog/django_blog/settings.py
========
    'rest_framework',
    'api',
>>>>>>>> 01a850dae2c214b543d28b8224f3639fdfa888ed:advanced_api_project/settings.py
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<<< HEAD:django_blog/django_blog/settings.py
ROOT_URLCONF = 'django_blog.urls'
========
ROOT_URLCONF = 'advanced_api_project.urls'
>>>>>>>> 01a850dae2c214b543d28b8224f3639fdfa888ed:advanced_api_project/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<<< HEAD:django_blog/django_blog/settings.py
WSGI_APPLICATION = 'django_blog.wsgi.application'
========
WSGI_APPLICATION = 'advanced_api_project.wsgi.application'
>>>>>>>> 01a850dae2c214b543d28b8224f3639fdfa888ed:advanced_api_project/settings.py


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
